### ISSUE TITLE
Capture errors before C* starts

### ISSUE THREAD

**Issue by EnigmaCurry** [datastax/cstar_perf#10]
There are a class of errors that Cassandra does not put into system.log, for instance environment errors. These should be captured and reported to the frontend.

For instance, if you set MAX_HEAP_SIZE without setting HEAP_NEWSIZE, you'll get this error:

    please set or unset MAX_HEAP_SIZE and HEAP_NEWSIZE in pairs (see cassandra-env.sh)

but that doesn't bubble up to the frontend, and you don't know why it failed.

**Comment by nastra** [comment]
Handled in #211
