### ISSUE TITLE
Have option to use existing clusters, without bootstrapping anything

### ISSUE THREAD

**Issue by EnigmaCurry** [datastax/cstar_perf#14]
It might be nice to be able to list clusters in the interface that you can run operations on, but that you can't install C* or bootstrap nodes on, for instance, clusters maintained outside of cstar_perf. 

stress_compare currently always tears down the cluster at the end of it's run, perhaps we need a no_bootstrap option. We already have a initial_destroy and leave_data option which may need to be rethought to handle this though.

**Comment by mishvaib** [comment]
Any progress on this?? If yes, please provide the details. Thanks a lot.

**Comment by rgknp** [comment]
This is a much desirable feature. Please let us know when it will be available. Thanks for the great work..!

**Comment by EnigmaCurry** [comment]
This seems out of scope for cstar_perf, so I will close this in favor of [CASSANDRA-7918](https://issues.apache.org/jira/browse/CASSANDRA-7918) which integrates this kind of thing into cassandra-stress itself. My branch mentioned in that ticket creates the same style of graphs that cstar_perf does.
