### ISSUE TITLE
WARNING:cassandra.cluster:Host 127.0.0.1 has been marked down

### ISSUE THREAD

**Issue by mohndoss** [datastax/cstar_perf#214]
Could you please tell me the reason why showing such warning message?

**Comment by mambocab** [comment]
Looks like this warning is logged by the Python driver:

https://github.com/datastax/python-driver/blob/1a6e7aadcd513dde58449f9403d1d8d05d40a119/cassandra/cluster.py#L1188

when a `Cluster` object has problems creating connections to a particular node:

https://github.com/datastax/python-driver/blob/1a6e7aadcd513dde58449f9403d1d8d05d40a119/cassandra/cluster.py#L1283-L1287

In general, if there's an error that isn't specific to `cstar_perf`, using the resources in the "Learn More" section of this page will be more helpful than asking in GitHub Issues on this repo:

http://cassandra.apache.org/

Closing.
