### ISSUE TITLE
GC stats not being collected

### ISSUE THREAD

**Issue by snazy** [datastax/cstar_perf#63]
Cassandra 2.0.14 + 2.1.4 changed bind address of JMX from 0.0.0.0 (any addr) to localhost only.
cassandra-stress tries to collect GC stats via JMX, which does not work since JMX is not reachable.

Let C* bind JMX to any-address so that GC stats can be collected (again).

**Comment by EnigmaCurry** [comment]
I thought I fixed this here: https://github.com/datastax/cstar_perf/commit/0a745f2e61d6f89f8e625942b1bc998817e57ca5

What stats specifically are missing?

Here's a recent run from you that looks like its picking it up:
http://cstar.datastax.com/graph?stats=7de68872-1c0c-11e5-9038-42010af0688f&metric=gc_mb&operation=1_write

**Comment by snazy** [comment]
Ah - yes. Partially :)

See http://cstar.datastax.com/tests/artifacts/e703f7cc-1c39-11e5-a699-42010af0688f/console 
The first two revisions are off 2.1 commits - the last is a 2.0 commit. And the last misses the GC stats.

**Comment by EnigmaCurry** [comment]
AFAIK stress can't pick up gc stats prior to 2.1. I'll try and confirm that though

**Comment by snazy** [comment]
Would it be possible to get the GC stats in the graph, too?

**Comment by EnigmaCurry** [comment]
They are? 

http://cstar.datastax.com/graph?stats=ae729c84-2656-11e5-ba8a-42010af0688f&metric=gc_count&operation=1_write&smoothing=1&show_aggregates=true&xmin=0&xmax=136.07&ymin=0&ymax=4.4

**Comment by snazy** [comment]
oops - strike my question (seems, i really need glasses)
