### ISSUE TITLE
Add support for hints_directory (CASSANDRA-6230)

### ISSUE THREAD

**Issue by aboudreault** [datastax/cstar_perf#85]
https://issues.apache.org/jira/browse/CASSANDRA-6230

--> hints_directory: /var/lib/cassandra/hint

**Comment by aboudreault** [comment]
@EnigmaCurry About the yaml configuration, just by adding it in our cluster_config.json will automatically add it in the cassandra.yaml if it is in the jython config keys, right?

So the issue with it now is that it will break current DSE support. I will work to make DSE also fetch it cassandra keys using jython, similar to what we currently do. Currently, it is just adding all the config options, so will break < dse 4.8.

**Comment by nastra** [comment]
I think we can close this issue here. https://github.com/datastax/cstar_perf/pull/169 is also taking care of cleaning up the hints directory
