### ISSUE TITLE
Clone test does not retain JVM version

### ISSUE THREAD

**Issue by belliottsmith** [datastax/cstar_perf#95]
Seems to get reset to oldest JDK 1.7 - this is only a tiny bug, but is bound to catch people out

**Comment by aboudreault** [comment]
yep, will fix tonight

**Comment by EnigmaCurry** [comment]
The JVM selector is also broken in #93. We should probably fix it there instead of on master, because that PR is almost ready to merge anyway.

**Comment by aboudreault** [comment]
I assume it has been rebased since the DSE work? I'll setup that branch
locally and fix it there.

**Comment by EnigmaCurry** [comment]
Yea, I did the rebase yesterday on top of DSE changes

**Comment by EnigmaCurry** [comment]
It might be a good idea to also make the latest java8 the default jvm for
new tests.

**Comment by aboudreault** [comment]
Fixed in #93.

**Comment by belliottsmith** [comment]
Great. Thanks!
